### ISSUE TITLE
Unauthorized through CIDR restrictions on the secret ID

### ISSUE THREAD

**Issue by alesstimec** [canonical/vault-k8s-operator#337]
### Bug Description

See discussion [here](https://matrix.to/#/!yAkGlrYcBFYzYRvOlQ:ubuntu.com/$iSh81WI9kAhzAnXzDoPjm4_yGu61Qcb8p7GnoC8Zeo8?via=ubuntu.com&via=matrix.org&via=mozilla.org)
```

### To Reproduce

See discussion [here](https://matrix.to/#/!yAkGlrYcBFYzYRvOlQ:ubuntu.com/$iSh81WI9kAhzAnXzDoPjm4_yGu61Qcb8p7GnoC8Zeo8?via=ubuntu.com&via=matrix.org&via=mozilla.org)

### Environment

microk8s

### Relevant log output

```shell
https://pastebin.canonical.com/p/Xk9qjgfCWG/
```

**Comment by Kayra1** [comment]
Looks like we don't resync with relations that are connected but never had a kv request [here](https://github.com/canonical/vault-k8s-operator/blob/5001a3fa416e67590793d97c6367b386c43bb528/src/charm.py#L414). We should be resyncing with every relation if any of the variables including the IP address changes, or remove or loosen the CIDR restriction.

**Comment by saltiyazan** [comment]
Hi @alesstimec 
#361 Is supposed to have fixed this.

**Comment by alesstimec** [comment]
Hi.. 

I still get this issue (but not due to CIDR restrictions).. It's just that the application fails to log in using provided credentials..

**Comment by saltiyazan** [comment]
> Hi..
> 
> I still get this issue (but not due to CIDR restrictions).. It's just that the application fails to log in using provided credentials..

Hi @alesstimec 

Could you please share more information? I can look into it.

**Comment by alesstimec** [comment]
Hi @saltiyazan,

when i relate JIMM to vault (using the vault-kv interface) it all works, JIMM is able to use vault to store secrets.. However as soon as the JIMM unit (k8s pod) gets recreated (with a different IP), JIMM is no longer able to log in using provided credentials..

Are there any logs i could provide to help debug this issue?

**Comment by saltiyazan** [comment]
Based on an offline discussion with @alesstimec 
The requirer charm was not updating the credentials secret when fetching it.
Here is a [PR](https://github.com/canonical/vault-k8s-operator/pull/385) to improve the documentation on how to use the library.
